spec_version: 1
kind: application

inputs:
- AWS_INSTANCE_TYPE: m5.large

infrastructure:
  connectivity:
    internal:
      - port_info:
          port: 27017
  compute:
    spec:            
      aws:
        instance_type: $AWS_INSTANCE_TYPE
        
configuration:
  start:
    script: mongodb-command.sh
  initialization:
    script: mongodb.sh  # will install mongodb 3.4
  healthcheck:
    timeout: 1000
    wait_for_ports: 27017
    
source:
  image:    
    ami:
      - id: ami-0194d18edbe11d815 # custom private ami
        region: us-west-1
        username: ubuntu
  os_type: linux
  
debugging: 
  connection_protocol: SSH